name: Doom Emacs CI

on:
  push:
    branches: # Added
      - main   # Added
    paths:
      - '**/*.el'
      - '**/*.org'
      - '.github/workflows/**'
      - '.dagger/**' # Also run if Dagger configuration changes
      - 'dagger.json'
  pull_request:
    paths:
      - '**/*.el'
      - '**/*.org'
      - '.github/workflows/**'
      - '.dagger/**' # Also run if Dagger configuration changes
      - 'dagger.json'

jobs:
  test-doom-config:
    name: Test Doom Emacs config boot via Dagger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Doom config
        uses: actions/checkout@v3

      - name: Setup Dagger
        uses: dagger/setup-dagger@v1 # Using v1, check for latest if possible

      - name: Run Dagger pipeline
        run: dagger call test --config-dir .
