name: Doom Emacs CI

on:
  push:
    paths:
      - '**/*.el'
      - '**/*.org'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**/*.el'
      - '**/*.org'
      - '.github/workflows/**'

jobs:
  test-doom-config:
    name: Test Doom Emacs config boot via Dagger
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Doom config
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Doom Emacs CI pipeline
        run: npm run pipeline
