name: Doom Emacs CI

on:
  push:
    paths:
      - '**/*.el'
      - '**/*.org'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**/*.el'
      - '**/*.org'
      - '.github/workflows/**'

#######################################################################
#  Doom Emacs CI
#  -------------
#  This workflow validates the configuration in three flavours:
#    1.  **lint**        – static `checkdoc` only              (fast)
#    2.  **skip-deps**   – full pipeline but reuse host Emacs  (medium)
#    3.  **full**        – build Emacs 30.1 from source        (slow)
#
#  The `full` variant is expensive, so it only runs on:
#    • pushes to the main branch
#    • *any* pull-request (to protect the default branch)
#######################################################################

jobs:
  doom-tests:
    name: "Doom Emacs • ${{ matrix.test_type }}"
    runs-on: ubuntu-latest

    # Drive three variations via a build matrix
    strategy:
      matrix:
        include:
          - test_type: lint
            env_flags: "LINT_ONLY=true"
          - test_type: skip-deps
            env_flags: "SKIP_DEPS=true"
          - test_type: full
            env_flags: ""        # full pipeline, no extra flags

    # Only run the **full** test on main branch or pull-requests
    if: ${{ !contains(matrix.test_type, 'full') || github.ref == 'refs/heads/main' || github.event_name == 'pull_request' }}

    steps:
      #-------------------------------------------------------------
      # Checkout repo
      #-------------------------------------------------------------
      - name: Checkout Doom config
        uses: actions/checkout@v3

      #-------------------------------------------------------------
      # Node (for Dagger TypeScript SDK)
      #-------------------------------------------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      #-------------------------------------------------------------
      # Install JS deps (dagger, ts-node, etc.)
      #-------------------------------------------------------------
      - name: Install dependencies
        run: npm ci

      #-------------------------------------------------------------
      # Run the requested pipeline flavour
      #-------------------------------------------------------------
      - name: Run Dagger pipeline – ${{ matrix.test_type }}
        env:
          # Propagate flags into the script (may be empty string)
          FLAGS: ${{ matrix.env_flags }}
        run: |
          echo "▶︎ running pipeline with flags: $FLAGS"
          eval "$FLAGS npm run pipeline"
